import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bukkis - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bukkis</h1>
        <ul>
          <li>Basharat</li>
          <li>Usman</li>
          <li>Kashif</li>
          <li>Khalid</li>
          <li>Idrees</li>
          <li>Saif</li>
        </ul>
        <div>
          <Image
            src="/basharat.jpeg"
            alt="Picture of the author"
            width={500}
            height={500}
          />
          <h1>100$ per night</h1>
          <p>
            contact here: <a href="tel:+923040963282">03040963282</a>
          </p>
        </div>
      </main>

      <footer className={styles.footer}>Bukkis @ 2022</footer>
    </div>
  );
}
