import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bukkis - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bukkis</h1>
        <ul>
          <li>Basharat</li>
          <li>Usman</li>
          <li>Kashif</li>
          <li>Khalid</li>
          <li>Idrees</li>
          <li>Saif</li>
        </ul>
      </main>

      <footer className={styles.footer}>Bukkis @ 2022</footer>
    </div>
  );
}
